name: telfaza
description: A movie tracking app, made using Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  rxdart: ^0.22.0
  flutter_spinkit: ^3.1.0
  url_launcher: ^5.0.3
  auto_size_text: ^2.0.1
  cached_network_image: ^1.0.0
  provider: ^3.0.0+1
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.1
  image_cropper: ^1.0.2
  # Dart
  quiver: ^2.0.3
  validators: ^2.0.0+1
  # Firebase stuff
  google_sign_in: ^4.0.4
  flutter_facebook_login: ^2.0.1
  firebase_auth: ^0.11.1+12
  cloud_firestore: ^0.12.9
  firebase_storage: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/

